# Copyright 2017 Dunbar Security Solutions, Inc.
#
# This file is part of Cyphon Engine.
#
# Cyphon Engine is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3 of the License.
#
# Cyphon Engine is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Cyphon Engine. If not, see <http://www.gnu.org/licenses/>.

sudo: required

language: python

env:
  - GEOIP_PATH=/home/travis/build/dunbarcyber/cyphon/GeoIP/

services:
  - docker

addons:
  postgresql: "9.6"
  apt:
    packages:
      - postgresql-9.6-postgis-2.3
  sauce_connect: true

python:
  - 3.6

install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install coveralls
  - pip install codacy-coverage

before_script:
  - psql -U postgres -c "create extension postgis"
  - docker-compose -f docker-compose.travis.yml up --build -d 
  - sleep 15  # wait for PostgreSQl and Elasticsearch to start

script:

  # copy GeoLite database to shared volume
  - docker exec cyphon_geoip_1 cp /usr/share/GeoIP/GeoLite2-City.mmdb /usr/share/cyphondock

  # use --keepdb to avoid OperationalError during teardown in case any
  # db connections are still open from threads in TransactionTestCases
  - cd cyphon
  - coverage run --source='.' --omit=*migrations*,*test* manage.py test --noinput --keepdb

after_success:
  - coverage
  - coveralls
  - codecov
  - coverage xml
  - python-codacy-coverage -r coverage.xml

after_script:
  - cd ../
  - docker-compose down
